sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly

services:
    - memcached
    - redis-server

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.7 WP_MULTISITE=0
    - WP_VERSION=3.7 WP_MULTISITE=1

# Old WordPress is incompatible with PHP 7.0+
matrix:
  exclude:
    - php: 7.0
      env: WP_VERSION=3.7 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=3.7 WP_MULTISITE=1
    - php: nightly
      env: WP_VERSION=3.7 WP_MULTISITE=0
    - php: nightly
      env: WP_VERSION=3.7 WP_MULTISITE=1
  allow_failures:
    - php: 7.0
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install -f apcu-4.0.11; fi
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
